apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.projects.uvr.name }}
  namespace: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
  - {{ .Values.projects.uvr.repo }}
  destinations:
    {{- range .Values.projects.uvr.stages }}
    {{- range .regions }}
    - namespace: uvr
      server: {{ .cluster }}
    {{- end }}
    {{- end }}
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
