apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: zum-adapter-emea-{{ .Values.env }}
spec:
  provider: azure
  secretObjects:
    - secretName: app.secret
      type: Opaque
      data:
        - objectName: idk-base-uri
          key: idk.base.uri
        - objectName: idk-customer-profile-uri
          key: idk.customer.profile.uri
        - objectName: idk-client-id
          key: idk.client.id
        - objectName: idk-client-secret
          key: idk.client.secret
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.keyvault.user }}
    keyvaultName: {{ .Values.keyvault.name }}
    objects:   |
      array:
        - |
          objectName: idk-base-uri
          objectAlias: "idk-base-uri"
          objectType: secret
        - |
          objectName: idk-customer-profile-uri
          objectAlias: "idk-customer-profile-uri"
          objectType: secret
        - |
          objectName: {{ .Values.namespace }}-idk-client-id
          objectAlias: "idk-client-id"
          objectType: secret
        - |
          objectName: {{ .Values.namespace }}-idk-client-secret
          objectAlias: "idk-client-secret"
          objectType: secret
    tenantId: "00000000-0000-0000-0000-000000000000"
