{{- range $stages := .Values.projects.uvr.stages }}
{{- range $regions := $stages.regions }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.projects.uvr.name }}-{{ $stages.name }}-{{ $regions.name }}
  namespace: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $.Values.projects.uvr.name }}
  source:
    repoURL: {{ $.Values.projects.uvr.repo }}
    targetRevision: HEAD
    path: helm
    helm:
      releaseName: {{ $.Values.projects.uvr.name }}
      valueFiles:
        - values/{{ $stages.name }}-{{ $regions.name }}.yaml
  destination:
    namespace: uvr
    server: {{ $regions.cluster }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
        - CreateNamespace=true
{{- end }}
{{- end }}
