apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adapter-dev-post-sync-hook
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $.Values.projects.adapter.name }}
  source:
    repoURL: {{ $.Values.ownRepo }}
    targetRevision: HEAD
    path: support/hooks/adapter/adapter-auto
    helm:
      releaseName: adapter-dev-post-sync-hook
  destination:
    namespace: adapter-auto
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
        - CreateNamespace=true