{{- range $stages := .Values.projects.adapter.stages }}
{{- range $regions := $stages.regions }}
{{- range $regions.namespaces }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.projects.adapter.name }}-{{ $stages.name }}-{{ $regions.name }}-{{ . }}
  namespace: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $.Values.projects.adapter.name }}
  source:
    repoURL: {{ $.Values.projects.adapter.repo }}
    targetRevision: HEAD
    path: helm
    helm:
      releaseName: {{ $.Values.projects.adapter.name }}
      valueFiles:
        - values/{{ . }}-{{ $regions.name }}-{{ $stages.name }}.yaml
  destination:
    namespace: {{ . }}
    server: {{ $regions.cluster }}
  {{ if eq "prod" $stages.name }}
  syncPolicy: {}
  {{ else }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
        - CreateNamespace=true
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
