apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adapter-prod-pre-sync-hook
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $.Values.projects.adapter.name }}
  source:
    repoURL: {{ $.Values.ownRepo }}
    targetRevision: HEAD
    path: support/hooks/adapter/adapter-manual
    helm:
      releaseName: adapter-prod-pre-sync-hook
  destination:
    namespace: adapter-manual
    name: in-cluster
